# Generated by Django 4.2.5 on 2023-09-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_bgm_comment_user_blogpost_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='like_count',
        ),
    ]
