# Generated by Django 4.2.5 on 2023-10-03 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0014_blogpost_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='like_users',
            field=models.ManyToManyField(related_name='like_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
